{% set name = "django-storages" %}
{% set version = "1.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-storages-{{ version }}.tar.gz
  sha256: c823dbf56c9e35b0999a13d7e05062b837bae36c518a40255d522fbe3750fbb4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - django >=2.2
    - python >=3.5
  run_constrained:
    - azure-storage-blob >=1.3.1,<12.0.0
    - boto3 >=1.4.4
    - dropbox >=7.2.1
    - google-cloud-storage >=1.15.0

test:
  imports:
    - storages
    - storages.backends
  commands:
    - pip check
    - pytest tests/integration/
  requires:
    - azure-storage-blob
    - pip
    - pytest
  source_files:
    - tests/integration/

about:
  home: https://github.com/jschneier/django-storages
  summary: Support for many storage backends in Django
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    django-storages is a project to provide a variety of storage backends in a single library.
    
    This library is usually compatible with the currently supported versions of Django.
    Check the Trove classifiers in setup.py to be sure.
  doc_url: https://django-storages.readthedocs.io/en/latest/
  dev_url: https://github.com/jschneier/django-storages

extra:
  recipe-maintainers:
    - BastianZim
    - cshaley
    - sannykr
