{% set name = "django-storages" %}
{% set version = "1.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ace80dbee311258453e30cd5cfd91096b834180ccf09bc1f4d2cb6d38d68571a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2
  run_constrained:
    - azure-storage-blob >=12.0.0
    - boto3 >=1.4.4
    - dropbox >=7.2.1
    - google-cloud-storage >=1.27.0

test:
  imports:
    - storages
    - storages.backends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jschneier/django-storages
  summary: Support for many storage backends in Django
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    django-storages is a project to provide a variety of storage backends in a single library.

    This library is usually compatible with the currently supported versions of Django.
    Check the Trove classifiers in setup.py to be sure.
  doc_url: https://django-storages.readthedocs.io/en/latest/
  dev_url: https://github.com/jschneier/django-storages

extra:
  recipe-maintainers:
    - rxm7706
    - BastianZim
    - cshaley
    - sannykr
