{% set name = "django-storages" %}
{% set version = "1.14.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-storages-{{ version }}.tar.gz
  sha256: 69aca94d26e6714d14ad63f33d13619e697508ee33ede184e462ed766dc2a73f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - django >=3.2
    - python >=3.7
  run_constrained:
    - azure-storage-blob >=12.0.0
    - boto3 >=1.4.4
    - dropbox >=7.2.1
    - google-cloud-storage >=1.27.0

test:
  imports:
    - storages
    - storages.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jschneier/django-storages
  summary: Support for many storage backends in Django
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    django-storages is a project to provide a variety of storage backends in a single library.

    This library is usually compatible with the currently supported versions of Django.
    Check the Trove classifiers in setup.py to be sure.
  doc_url: https://django-storages.readthedocs.io/en/latest/
  dev_url: https://github.com/jschneier/django-storages

extra:
  recipe-maintainers:
    - rxm7706
    - BastianZim
    - cshaley
    - sannykr
